### ISSUE TITLE
Period not parsed correctly "...is an unknown value" "schedule name is unknown"

### ISSUE THREAD

**Issue by e-power** [aws-solutions/instance-scheduler-on-aws#228]
Hi - I am having an issue where the period config doesn't be seem to be read properly.  The schedule and period is as below

```
      {
         "RetainRunning": false,
         "Enforced": true,
         "Hibernate": false,
         "Description": "Day to day office hours of eem including holidays",
         "ConfiguredInStack": "arn:aws:cloudformation:...stack/....",
         "StopNewInstances": true,
         "Periods": [
            "eem-office-hours-incl-holidays-21-period-0011",
            "eem-office-hours-incl-holidays-21-period-0001",
            "eem-office-hours-incl-holidays-21-period-0003",
            "eem-office-hours-incl-holidays-21-period-0002",
            "eem-office-hours-incl-holidays-21-period-0009",
            "eem-office-hours-incl-holidays-21-period-0012",
            "eem-office-hours-incl-holidays-21-period-0004",
            "eem-office-hours-incl-holidays-21-period-0008",
            "eem-office-hours-incl-holidays-21-period-0005",
            "eem-office-hours-incl-holidays-21-period-0010",
            "eem-office-hours-incl-holidays-21-period-0006",
            "eem-office-hours-incl-holidays-21-period-0007"
         ],
         "Timezone": "Europe/Berlin",
         "Type": "schedule",
         "Name": "eem-office-hours-incl-holidays-21"
      }
```

```
{
         "Description": "July, Schedule eem-office-hours-incl-holidays-21 period 7, do not delete or update manually",
         "Monthdays": [
            "1-31"
         ],
         "Months": [
            "7"
         ],
         "Weekdays": [
            "mon-fri"
         ],
         "Begintime": "07:15",
         "Endtime": "18:30",
         "Type": "period",
         "Name": "eem-office-hours-incl-holidays-21-period-0007"
      }
```
      
 And in CloudWatchEventHandler cloudwatch logs I see this
 `ERROR : "1-31" is an unknown value`
 
 In my rds cloudwatch log I also see
 `WARNING : Skipping instance RDS:.... in region eu-central-1 for account ....., schedule name "eem-office-hours-incl-holidays-21" is unknown`
 
 Do you know what might be wrong here?

**Comment by arieleeuw** [comment]
Please try to specify Monthdays, Weekdays and Months as strings instead of Arrays of strings.

**Comment by e-power** [comment]
How so? It is passed in via cloudformation like so
```
  eemOfficeHoursInclHolidays21:
    Type: Custom::ServiceInstanceSchedule
    Properties:
      Name: eem-office-hours-incl-holidays-21
      NoStackPrefix: 'True'
      Description: Day to day office hours of eem including holidays
      ServiceToken: !GetAtt InstanceSchedulerLambda.Arn
      Enforced: 'True'
      Timezone: Europe/Berlin
      Periods:
        - Description: January
          Months: 1
          WeekDays: 'mon-fri'
          MonthDays: '2-5,7-31'
          BeginTime: '07:15'
          EndTime: '18:30'
 ```

**Comment by Nico-DB** [comment]
@e-power : Hi,
we are facing some kind of a similar issue. When defining **MonthDays** which exceeds 27, you are not able to define it as a _range_.
For example the following does not work:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ServiceTokenSchedule:
    Description: Token
    Type: String
Resources:
  FeoAUUTC:
    Type: Custom::ServiceInstanceSchedule
    Properties:
      Description: FeoAUUTC
      ServiceToken: !Ref ServiceTokenSchedule
      Enforced: 'True'
      Timezone: Europe/Berlin
      Periods:
      - Description: Feo AU Up April
        Months: apr
        MonthDays: 6-30

```

This does work:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ServiceTokenSchedule:
    Description: Token
    Type: String
Resources:
  FeoAUUTC:
    Type: Custom::ServiceInstanceSchedule
    Properties:
      Description: FeoAUUTC
      ServiceToken: !Ref ServiceTokenSchedule
      Enforced: 'True'
      Timezone: Europe/Berlin
      Periods:
      - Description: Feo AU Up April
        Months: apr
        MonthDays: 6-27,28,29,30
```


I know that this is a bug since a long time. What´s new for me is that in the passed the Cloudformation-Stack failed to create and told me that 30 is an unknown value. Which it does not anymore. 
Is it possible to either fix this issue or hand over the error back to cloudformation again?
