### ISSUE TITLE
Invalid PhysicalResourceId

### ISSUE THREAD

**Issue by kenlawrie1** [aws-solutions/instance-scheduler-on-aws#339]
Hello,
I have deployed AWS instance Scheduler v1.4.1 for my Client, and all works as expected except:

- When I use  'Custom::ServiceInstanceSchedule' to create schedules I intermittently get the CloudFormation error 'Invalid PhysicalResourceId', and a retry of the deployment works the second time. No other error messages anywhere.

From my investigation, this is looking like something that is going wrong in the Lambda function, however there are no errors I can see in the logs for this ServiceInstanceSchedule handler

Config that is different from the sample is:

I'm using the resource names `Schedule001`, `Schedule002` and `Schedule003`, and `NoStackPrefix : 'True''
```
  Schedule001:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: work-day-aedt-6am-8pm-on
      Description: Description
      Enforced: 'True'

      NoStackPrefix: 'True'
      ServiceToken: !Ref ServiceToken 
      Timezone: !Ref DefaultTimezone
      Metrics: 'True' # 

      Periods:
      ...
      ...
```
