### ISSUE TITLE
It seems to reverse the schedules when running in some scenarios

### ISSUE THREAD

**Issue by HSchmale16** [aws-solutions/instance-scheduler-on-aws#411]
I have a schedule that seems to be miss-reported in the cli `describe-schedule-usage`. It should run all day every 3rd Tuesday of the month, and from 5am to 7pm the rest of the week. Yet the periods don't seem to be additive. Here's the cloud formation I used to create it.

```
  AmericaWeekdayScheduleDev:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      Name: US-DEV-BUSINESS-HOURS-WEEKDAYS-ONLY
      NoStackPrefix: 'True'
      Description: United States Business Hours on Mon-Fri, off on weekends
      ServiceToken: !Ref ServiceToken
      Enforced: 'True'
      Hibernate: 'True'
      Timezone: !Ref RegionTzAmerica
      Periods:
        - Description: Must run all day every 3rd Tuesday
          WeekDays: tue#3
          BeginTime: '00:00'
          EndTime: '05:00'
        - Description: Opening hours on weekdays
          BeginTime: '05:00'
          EndTime: '19:00'
          WeekDays: mon-fri
        - Description: Must run all day every 3rd Tuesday
          WeekDays: tue#3
          BeginTime: '19:00'
          EndTime: '23:59'
```

As it stands the output says it starts at 7pm and dies at midnight everyday. A schedule with just the middle period produces output as expected. Additionally the 3rd Tuesday runs from 5am to midnight instead of starting at midnight.

We are currently running version `(SO0030) - aws-instance-scheduler, version v1.3.2`

I've attached the output of `describe-schedule-usage` to this issue.
[results.txt](https://github.com/aws-solutions/aws-instance-scheduler/files/11055145/results.txt)
