### ISSUE TITLE
Unable to update schedules and periods via CDK

### ISSUE THREAD

**Issue by ramarahul** [aws-solutions/instance-scheduler-on-aws#453]
I've followed the readme and deployed the CDK application for v1.4.2 solution. Now I want to update the schedules and periods through CDK and not via console or using scheduler-cli directly. However, I can't see any option to do so. I tried to update the ``` setup_demo_data.py``` file and hoped the DynamoDB would reflect the changes I made. Unfortunately, that did not work. Is there anything I can do so that I can update the schedules and periods via changing code in Git instead of doing manual operations of CRUD on the DB.

**Comment by ramarahul** [comment]
Any help with this @gockle @CrypticCabub ?

**Comment by CrypticCabub** [comment]
Hi @ramarahul 

We do not have a construct for creating schedules through CDK directly, but we do have a custom resource that will allow you to manage schedules using Infrastructure as Code via CloudFormation templates.

You can find the documentation for this in our implementation guide [here](https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/custom-resource.html)


And here is an example of how you can implement the IG's example schedule using the custom resource (note that this version takes in the ServiceToken ARN as an input parameter to make managing it easier)
```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ServiceInstanceScheduleServiceTokenARN:
    Type: String
    Description: (Required) service token arn taken from InstanceScheduler outputs
Metadata:
  'AWS::CloudFormation::Designer': {}
Resources:
  StopOnWeekends:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      NoStackPrefix: 'True'
      Name: mon-9am-fri-5pm
      Description: start instances at 9am on monday and stop them at 5pm on friday
      ServiceToken: !Ref ServiceInstanceScheduleServiceTokenARN
      Timezone: America/New_York
      Periods:
      - Description: 9am monday start
        BeginTime: '09:00'
        EndTime: '23:59'
        WeekDays: mon
      - Description: all day tuesday-thursday
        WeekDays: tue-thu
      - Description: 5pm friday stop
        BeginTime: '00:00'
        EndTime: '16:59'
        WeekDays: fri
```
