### ISSUE TITLE
Stop and Restart EC2 once in a month; normal times EC2 is in running mode

### ISSUE THREAD

**Issue by ahkai86** [aws-solutions/instance-scheduler-on-aws#468]
Hi everyone, 

Need a feature to Stop and Start EC2 once in a month. Running instance scheduler-v1.5.0 currently

Schedule
```
{
  "type": {
    "S": "schedule"
  },
  "name": {
    "S": "restart-ec2-monthly"
  },
  "description": {
    "S": "restart-ec2-monthly"
  },
  "enforced": {
    "S": "True"
  },
  "periods": {
    "SS": [
      "monthly1",
      "monthly2"
    ]
  },
  "timezone": {
    "S": "Asia/Singapore"
  }
}
```

Periods, currently i have 2 periods which :
First period toggle running 00:00 to 4:00 (shutdown at 4am) 3rd monday of the month
Second period toggle running 04:10 to 23:59 (startup at 410am) 3rd monday of the month
```
{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "monthly1"
  },
  "begintime": {
    "S": "00:00"
  },
  "description": {
    "S": "trigger EC2 running timing 1"
  },
  "endtime": {
    "S": "04:00"
  },
  "weekdays": {
    "SS": [
      "mon#3"
    ]
  }
}
```

```
{
  "type": {
    "S": "period"
  },
  "name": {
    "S": "monthly2"
  },
  "begintime": {
    "S": "04:10"
  },
  "description": {
    "S": "trigger EC2 running timing 1"
  },
  "endtime": {
    "S": "23:59"
  },
  "weekends": {
    "SS": [
      "mon#3"
    ]
  }
}

```

Not sure if the above following configurations works, my agenda is to shutdown and restart again the EC2 every 3rd monday of the month.

Please kindly advice or if anyone has any insights, Thanks in advance and cheers!

**Comment by CrypticCabub** [comment]
hi @ahkai86

Instance Scheduler unfortunately does not currently handle explicit "stop periods" very well. You have the right idea for how to setup what you want on the specific day, but you would also need to explicitly handle all the other days on the calendar to avoid stopping the instance after midnight

Using the custom resource to manage the schedule in an Infrastructure as Code fashion I would recommend a schedule that looks something like this:
_disclaimer: I have only verified that this template deploys the correct schedule, but you will still want to confirm that the schedule itself restarts your instance as expected when the time comes_
```
AWSTemplateFormatVersion: 2010-09-09
Parameters:
  ServiceInstanceScheduleServiceTokenARN:
    Type: String
    Description: (Required) service token arn taken from InstanceScheduler outputs
Metadata:
  'AWS::CloudFormation::Designer': {}
Resources:
  restartOn3rdMonday:
    Type: 'Custom::ServiceInstanceSchedule'
    Properties:
      ServiceToken: !Ref ServiceInstanceScheduleServiceTokenARN #do not edit this line
      NoStackPrefix: 'True'
      Description: 'restart at 4am on the 3rd monday of every month'
      Timezone: 'Asia/Singapore'
      Periods:
      - Description: '3rd monday, midnight-4am'
        BeginTime: '0:00'
        EndTime: '4:00'
        WeekDays: 'Mon#3'
      - Description: '3rd monday, 410am-midnight'
        BeginTime: '4:10'
        EndTime: '23:59'
        WeekDays: 'Mon#3'
      - Description: 'running every other day of the week'
        WeekDays: 'Tue-Sun'
      - Description: 'running every other monday'
        WeekDays: 'Mon#1,Mon#2,Mon#4,Mon#5'
```
If you deploy this template in CloudFormation, it will create a schedule for you with the name "restartOn3rdMonday" that will be managed by the CloudFormation stack

You can add `Enforced: 'True'` to the base properties if you want an enforced schedule, but I would recommend against that unless you specifically want to prevent stopping the instance at all during normal operating hours

The documentation for the CustomResource can be found on the implementation guide here:
https://docs.aws.amazon.com/solutions/latest/instance-scheduler-on-aws/custom-resource.html

And if you go to deploy this cfn template as-is, you can find the ServiceToken parameter in the outputs of your Instance Scheduler hub stack
